### ISSUE TITLE
GNIRS addIlluminationMask should expose the max offset on the positioning.

### ISSUE THREAD

**Issue by KathleenLabrie** [GeminiDRSoftware/DRAGONS#292]
The internal function _position_illum_mask has the argument max_dy which defaults to 20.  This limits the possible offset in y between the exposed region and the position of the illumination mask.  This limit is necessary to avoid picking up ghost keyholes way off the center of the array.

However, in some cases, from the archive, the keyhole was in reality way off the center, beyond the 20-pixel limit.  GNIRS components move a lot.   In those cases, the 20-pix limit makes the reduction impossible.

A solution (tested quickly using the integration test data) is to increase that limit.  Instead of increasing the default though, I propose that we add an input parameter to `addIlluminationMask` for GNIRS that would allow the poor user of GNIRS in imaging mode to increase the limit when needed.

Shouldn't be too hard to do, also not urgent at all.  I'll probably get to it eventually, but not today, so logging this here for safe keeping.

**Comment by chris-simpson** [comment]
I'm going to close this. The original method of determining the keyhole positional offset was poor and it's now much improved. The user can provide a shift of up to 100 pixels compared to the automated position (which is, of course, what they see in the DQ plan after running the primitive so it's best to apply that shift rather than the shift from the nominal position), which should cover all eventualities. I asked for your pathological datasets and included them in the tests. If there are further issues we can address them but the code has changed so much it's no longer the same problem.
