### ISSUE TITLE
Runtime warning about true_divide in `flagCosmicRays`

### ISSUE THREAD

**Issue by KathleenLabrie** [GeminiDRSoftware/DRAGONS#338]
I’m encountering the following warnings when I run the recipe with flagCosmicRays:
```
   PRIMITIVE: flagCosmicRays
   -------------------------
      PRIMITIVE: tileArrays
      ---------------------
      Array maps to [1:1024,1:512]
      Array maps to [1:1024,1:512]
      Array maps to [1:1024,1:512]
      .
/Users/klabrie/condaenvs/susd3.9_20211015/lib/python3.9/site-packages/astropy/visualization/mpl_normalize.py:164: RuntimeWarning: divide by zero encountered in true_divide
  np.true_divide(values, self.vmax - self.vmin, out=values)
/Users/klabrie/condaenvs/susd3.9_20211015/lib/python3.9/site-packages/astropy/visualization/mpl_normalize.py:164: RuntimeWarning: invalid value encountered in true_divide
  np.true_divide(values, self.vmax - self.vmin, out=values)
```

Chris' comment from Slack:

>  I find it a bit concerning. I don't see any division in the primitive so it must be coming from one of the two `fit1D` calls or the `detect_cosmics` call or the `plot_cosmics` call. It needs to be narrowed down. I haven't worked on this primitive.

Assigning to Daniel who worked on `flagCosmicRays`.

**Comment by DBerke** [comment]
Having looked into it: the warnings come from the call to `matplotlib.pyplot.Figure.savefig()` which saves the plot of the arrays to disk. It's not present when `bkgmodel='both'`, so it's something to do with the figure trying to normalize an array of zeroes when either the object or sky line fit (or both) are absent. It has nothing to do with the science data or reduction process, however, and can be safely ignored. I don't see a simple way to prevent it from happening when not using both background fits, so I've added a context manager to that line only which ignores NumPy errors related to 'divide by zero' and 'invalid value'  errors; it should be fixed in [this commit](https://github.com/GeminiDRSoftware/DRAGONS/commit/3badea5675626926b80919b6b804f9e26c3cb6ad).
