### ISSUE TITLE
Expose threshold for flagging resampled bad pixels

### ISSUE THREAD

**Issue by chris-simpson** [GeminiDRSoftware/DRAGONS#444]
`transform.resample_from_wcs()` has a `threshold` parameter that determines whether a pixel that has some contribution from a DQ-flagged pixel should also be flagged. This threshold is 0.01 by default but should probably be more conservative, e.g. 0.001. It should also be exposed to the user as a parameter, maybe `dq_threshold`.

The places this needs to be done are:
1. `Spect.distortionCorrect()`
2. `Spect.resampleToCommonFrame()`
3. `Image.resampleToCommonFrame()`
4. `Image.shiftImages()`
5. `GMOSNodAndShuffle.combineNodAndShuffleBeams()`

Add the parameter to these primitives and pass it to `transform.resample_from_wcs()` (via `Image._resample_to_new_frame()` in the case of the `Image` primitives).

`resample_from_wcs()` is called elsewhere but only as an intermediate step (e.g., displaying images, mosaicking prior to flat normalization).

Regression tests are likely to fail because of this so the references will need updating.

**Comment by DBerke** [comment]
I've pushed a [commit](https://github.com/GeminiDRSoftware/DRAGONS/commit/159439b43029d0fd9136e4d30e10fa963d6f9e7f) to handle this. When Jenkins is back up I'll need to copy over three updated reference files for `/geminidr/gsaoi/tests/test_gsaoi_image.py::test_gsaoi_adjust_wcs_no_refcat`, which will cause that test to fail in the meantime if anyone else tries running it locally. Otherwise, all tests should pass; the commit itself removes a test case that fails with the new `dq_threshold` value until we have time to look into the whole thing more closely. I don't know if we want to close this issue now (since the issue has been fixed), or leave it open until the files have been moved as a reminder.
